version: '3.7'
service:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    networks:
      - febnine-net
    depends_on:
      - mysql
  mysql:
    container_name: febnine-mysql
    image: mysql
    env_file:
      - .env.
