version: '3.7'
services:
  nest:
    image: th2912/nestboard
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - board
  mysql:
    image: mysql
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=board
    ports:
      - '3306:3306'
    networks:
      - board

volumes:
  db: {}

networks:
  board: {}
